import { PropertyModel } from './property.model';

export const data2: PropertyModel[] = [
  {
    title: '1st Floor',
    city: 'São Julião do Tojal',
    address: '75342 Eagan Alley',
    size: 55,
    rooms: 6,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Apt 991',
    city: 'São Julião do Tojal',
    address: '258 Orin Center',
    size: 64,
    rooms: 4,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'Suite 53',
    city: 'Maoping',
    address: '3862 Forster Junction',
    size: 115,
    rooms: 6,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Room 501',
    city: 'Maoping',
    address: '15 Schlimgen Terrace',
    size: 72,
    rooms: 2,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'Room 53',
    city: 'Xinglong',
    address: '2824 Browning Trail',
    size: 84,
    rooms: 4,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'Room 74',
    city: 'Queimados',
    address: '33710 International Trail',
    size: 88,
    rooms: 1,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'PO Box 22384',
    city: 'Denver',
    address: '93457 Sundown Trail',
    size: 107,
    rooms: 4,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: '16th Floor',
    city: 'Isaka',
    address: '03 Lake View Center',
    size: 75,
    rooms: 6,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'Room 1488',
    city: 'Lorena',
    address: '4013 Alpine Court',
    size: 85,
    rooms: 3,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'PO Box 88460',
    city: 'Xintang',
    address: '881 Erie Pass',
    size: 119,
    rooms: 4,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Apt 1280',
    city: 'Yabuli',
    address: '333 Shopko Hill',
    size: 109,
    rooms: 3,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Suite 71',
    city: 'Karangmangu',
    address: '1467 Pawling Circle',
    size: 116,
    rooms: 5,
    isRented: false,
    isPetsAllowed: true,
  },
  {
    title: 'Apt 688',
    city: 'Moss',
    address: '372 Rigney Trail',
    size: 28,
    rooms: 5,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Suite 98',
    city: 'Sebba',
    address: '794 Westerfield Junction',
    size: 41,
    rooms: 1,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: 'Suite 26',
    city: 'Binguang',
    address: '5 Crowley Circle',
    size: 102,
    rooms: 5,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: '1st Floor',
    city: 'Xicheng',
    address: '7846 Old Shore Court',
    size: 56,
    rooms: 2,
    isRented: false,
    isPetsAllowed: false,
  },
  {
    title: '5th Floor',
    city: 'Maungatapere',
    address: '903 Delladonna Parkway',
    size: 59,
    rooms: 3,
    isRented: false,
    isPetsAllowed: true,
  },
];
