import { PropertyModel } from './property.model';

export const data: PropertyModel[] = [
  {
    title: 'Suite 91',
    city: 'Turangi',
    address: '860 Nobel Junction',
    size: 58,
    rooms: 3,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?nature,water',
  },
  {
    title: 'Room 1291',
    city: 'Linquan',
    address: '1 Atwood Alley',
    size: 54,
    rooms: 4,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?architecture,building',
  },
  {
    title: 'Room 7',
    city: 'Sacramento',
    address: '16 Charing Cross Park',
    size: 110,
    rooms: 6,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?city,skyline',
  },
  {
    title: 'Room 1963',
    city: 'Kampungruweh',
    address: '78 Mesta Hill',
    size: 99,
    rooms: 2,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?mountain,landscape',
  },
  {
    title: 'Apt 1469',
    city: 'Belozërsk',
    address: '00182 Corscot Park',
    size: 60,
    rooms: 6,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?building,office',
  },
  {
    title: 'Room 97',
    city: 'Nāḩiyat as Sab‘ Biyār',
    address: '050 Everett Center',
    size: 96,
    rooms: 2,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?urban,street',
  },
  {
    title: 'Suite 96',
    city: 'Tekeli',
    address: '70263 Shoshone Way',
    size: 107,
    rooms: 3,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?interior,living-room',
  },
  {
    title: 'Room 1620',
    city: 'Lorena',
    address: '2 Browning Drive',
    size: 117,
    rooms: 6,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?bedroom,furniture',
  },
  {
    title: 'Room 1457',
    city: 'Xintang',
    address: '07 Cottonwood Road',
    size: 111,
    rooms: 1,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?apartment,modern',
  },
  {
    title: 'Apt 1950',
    city: 'Neklyudovo',
    address: '9 Vahlen Drive',
    size: 89,
    rooms: 2,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?architecture,home',
  },
  {
    title: 'Suite 54',
    city: 'Pandian',
    address: '7 Duke Pass',
    size: 40,
    rooms: 6,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?building,skyscraper',
  },
  {
    title: 'Apt 822',
    city: 'Zhishan',
    address: '132 Chinook Place',
    size: 112,
    rooms: 6,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?building,architecture',
  },
  {
    title: 'PO Box 67571',
    city: 'Debrecen',
    address: '16 Tony Circle',
    size: 119,
    rooms: 2,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?cityscape,city',
  },
  {
    title: 'PO Box 15032',
    city: 'Ad Dilam',
    address: '0 Surrey Road',
    size: 113,
    rooms: 2,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?living-room,home',
  },
  {
    title: 'Suite 21',
    city: 'Neni',
    address: '2 Donald Pass',
    size: 43,
    rooms: 2,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?bedroom,interior',
  },
  {
    title: 'Apt 386',
    city: 'Pitogo',
    address: '16700 Comanche Point',
    size: 89,
    rooms: 5,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?apartment,building',
  },
  {
    title: 'Suite 56',
    city: 'Xinzhuang',
    address: '0 Haas Crossing',
    size: 107,
    rooms: 6,
    isPetsAllowed: true,
    imgUrl: 'https://source.unsplash.com/600x400/?urban,street',
  },
  {
    title: 'PO Box 8026',
    city: 'Chirongui',
    address: '1 Hanson Trail',
    size: 35,
    rooms: 6,
    isPetsAllowed: false,
    imgUrl: 'https://source.unsplash.com/600x400/?cityscape,city',
  },
];
